import { Building, MapPin, Award } from 'lucide-react';
import { ProjectPageConfig, ConstructionProject } from '../types/ProjectTypes';
import { sampleGAAProjects } from '../data/gaaProjectsData';

// Sample data for Locally-Funded Projects
export const sampleLocallyFundedProjects: ConstructionProject[] = [
  {
    id: 'local-001',
    projectTitle: 'Campus Road Infrastructure Improvement',
    dateStarted: '2024-01-15',
    projectDuration: '8 months',
    targetDateCompletion: '2024-09-15',
    fundingSource: 'Local Government Unit',
    approvedBudget: 3500000,
    appropriation: 3500000,
    obligation: 2800000,
    totalLaborCost: 1200000,
    totalProjectCost: 3500000,
    disbursement: 1750000,
    progressAccomplishment: 65,
    status: 'Ongoing',
    remarks: 'Road improvement project to enhance campus accessibility',
    category: 'locally-funded',
    location: 'Main Campus',
    localGovernmentUnit: 'Butuan City',
    projectManager: 'Engr. Maria Santos'
  },
  {
    id: 'local-002',
    projectTitle: 'Student Dormitory Renovation Phase 1',
    dateStarted: '2024-02-01',
    projectDuration: '6 months',
    targetDateCompletion: '2024-08-01',
    fundingSource: 'Provincial Government',
    approvedBudget: 2800000,
    appropriation: 2800000,
    obligation: 2800000,
    totalLaborCost: 980000,
    totalProjectCost: 2800000,
    disbursement: 2240000,
    progressAccomplishment: 80,
    status: 'Ongoing',
    remarks: 'Renovation of dormitory facilities to improve student accommodation',
    category: 'locally-funded',
    location: 'Campus Extension',
    localGovernmentUnit: 'Agusan del Norte',
    projectManager: 'Engr. Juan Dela Cruz'
  },
  {
    id: 'local-003',
    projectTitle: 'Library Extension Construction',
    dateStarted: '2023-09-15',
    projectDuration: '12 months',
    targetDateCompletion: '2024-09-15',
    fundingSource: 'City Government',
    approvedBudget: 5200000,
    appropriation: 5200000,
    obligation: 5200000,
    totalLaborCost: 1820000,
    totalProjectCost: 5200000,
    disbursement: 5200000,
    progressAccomplishment: 100,
    status: 'Completed',
    remarks: 'Additional library space for expanding collection and study areas',
    category: 'locally-funded',
    location: 'Academic Complex',
    localGovernmentUnit: 'Butuan City',
    projectManager: 'Engr. Ana Rodriguez'
  },
  {
    id: 'local-004',
    projectTitle: 'Campus Drainage System Upgrade',
    dateStarted: '2024-03-01',
    projectDuration: '4 months',
    targetDateCompletion: '2024-07-01',
    fundingSource: 'Municipal Government',
    approvedBudget: 1800000,
    appropriation: 1800000,
    obligation: 1440000,
    totalLaborCost: 630000,
    totalProjectCost: 1800000,
    disbursement: 720000,
    progressAccomplishment: 40,
    status: 'Ongoing',
    remarks: 'Improvement of campus drainage to prevent flooding during rainy season',
    category: 'locally-funded',
    location: 'Campus-wide',
    localGovernmentUnit: 'Cabadbaran City',
    projectManager: 'Engr. Roberto Garcia'
  },
  {
    id: 'local-005',
    projectTitle: 'Sports Complex Facility Enhancement',
    dateStarted: '2024-04-15',
    projectDuration: '10 months',
    targetDateCompletion: '2025-02-15',
    fundingSource: 'Regional Government',
    approvedBudget: 4500000,
    appropriation: 4500000,
    obligation: 900000,
    totalLaborCost: 1575000,
    totalProjectCost: 4500000,
    disbursement: 450000,
    progressAccomplishment: 15,
    status: 'Planning',
    remarks: 'Enhancement of sports facilities to support athletic programs',
    category: 'locally-funded',
    location: 'Athletic Field',
    localGovernmentUnit: 'Butuan City',
    projectManager: 'Engr. Patricia Lim'
  }
];

// Sample data for Special Grants Projects
export const sampleSpecialGrantsProjects: ConstructionProject[] = [
  {
    id: 'special-001',
    projectTitle: 'Green Campus Sustainability Initiative',
    dateStarted: '2024-01-10',
    projectDuration: '18 months',
    targetDateCompletion: '2025-07-10',
    fundingSource: 'World Bank Environment Grant',
    approvedBudget: 8500000,
    appropriation: 8500000,
    obligation: 6800000,
    totalLaborCost: 2975000,
    totalProjectCost: 8500000,
    disbursement: 4250000,
    progressAccomplishment: 45,
    status: 'Ongoing',
    remarks: 'Comprehensive sustainability project including solar panels, waste management systems, and green buildings',
    category: 'special-grants',
    grantType: 'Special Grant',
    partnerOrganization: 'World Bank',
    projectManager: 'Dr. Elena Martinez',
    expectedRevenue: 0
  },
  {
    id: 'special-002',
    projectTitle: 'University-Industry Innovation Hub',
    dateStarted: '2024-02-15',
    projectDuration: '12 months',
    targetDateCompletion: '2025-02-15',
    fundingSource: 'Private Industry Partnership',
    approvedBudget: 12000000,
    appropriation: 12000000,
    obligation: 9600000,
    totalLaborCost: 4200000,
    totalProjectCost: 12000000,
    disbursement: 6000000,
    progressAccomplishment: 60,
    status: 'Ongoing',
    remarks: 'Public-private partnership for establishing innovation and research facilities',
    category: 'special-grants',
    grantType: 'Partnership',
    partnerOrganization: 'Tech Innovation Corp.',
    projectManager: 'Engr. Michael Chen',
    expectedRevenue: 2500000
  },
  {
    id: 'special-003',
    projectTitle: 'Student Entrepreneurship Center',
    dateStarted: '2023-11-01',
    projectDuration: '8 months',
    targetDateCompletion: '2024-07-01',
    fundingSource: 'DOST Innovation Grant',
    approvedBudget: 4500000,
    appropriation: 4500000,
    obligation: 4500000,
    totalLaborCost: 1575000,
    totalProjectCost: 4500000,
    disbursement: 4500000,
    progressAccomplishment: 100,
    status: 'Completed',
    remarks: 'Establishment of entrepreneurship center to support student startups and business incubation',
    category: 'special-grants',
    grantType: 'Special Grant',
    partnerOrganization: 'Department of Science and Technology',
    projectManager: 'Prof. Sarah Johnson',
    expectedRevenue: 1200000
  },
  {
    id: 'special-004',
    projectTitle: 'Campus Conference and Events Facility',
    dateStarted: '2024-03-01',
    projectDuration: '10 months',
    targetDateCompletion: '2025-01-01',
    fundingSource: 'Revenue Generation Initiative',
    approvedBudget: 15000000,
    appropriation: 15000000,
    obligation: 12000000,
    totalLaborCost: 5250000,
    totalProjectCost: 15000000,
    disbursement: 7500000,
    progressAccomplishment: 35,
    status: 'Ongoing',
    remarks: 'Multi-purpose facility for conferences, events, and commercial rentals to generate university revenue',
    category: 'special-grants',
    grantType: 'Income-Generating',
    partnerOrganization: 'CSU Revenue Development Office',
    projectManager: 'Arch. David Rodriguez',
    expectedRevenue: 8000000
  },
  {
    id: 'special-005',
    projectTitle: 'International Research Collaboration Center',
    dateStarted: '2024-04-01',
    projectDuration: '24 months',
    targetDateCompletion: '2026-04-01',
    fundingSource: 'ASEAN Education Cooperation Grant',
    approvedBudget: 18000000,
    appropriation: 18000000,
    obligation: 3600000,
    totalLaborCost: 6300000,
    totalProjectCost: 18000000,
    disbursement: 1800000,
    progressAccomplishment: 10,
    status: 'Planning',
    remarks: 'Advanced research facility to support international collaboration and joint research projects',
    category: 'special-grants',
    grantType: 'Special Grant',
    partnerOrganization: 'ASEAN University Network',
    projectManager: 'Dr. Maria Fernandez',
    expectedRevenue: 3500000
  },
  {
    id: 'special-006',
    projectTitle: 'Digital Innovation Laboratory',
    dateStarted: '2024-01-20',
    projectDuration: '6 months',
    targetDateCompletion: '2024-07-20',
    fundingSource: 'Tech Partnership Fund',
    approvedBudget: 6800000,
    appropriation: 6800000,
    obligation: 6120000,
    totalLaborCost: 2380000,
    totalProjectCost: 6800000,
    disbursement: 5440000,
    progressAccomplishment: 85,
    status: 'Ongoing',
    remarks: 'State-of-the-art digital laboratory for computer science and IT programs with industry partnerships',
    category: 'special-grants',
    grantType: 'Partnership',
    partnerOrganization: 'Microsoft Philippines',
    projectManager: 'Prof. James Wilson',
    expectedRevenue: 1800000
  }
];

// Page configurations for each funding type
export const projectPageConfigs: Record<string, ProjectPageConfig> = {
  'gaa-funded': {
    category: 'gaa-funded',
    title: 'GAA-Funded Projects',
    subtitle: 'National Government Infrastructure Development',
    icon: Building,
    defaultFundingSource: 'General Appropriations Act (GAA)',
    sampleProjects: sampleGAAProjects
  },
  'locally-funded': {
    category: 'locally-funded',
    title: 'Locally-Funded Projects',
    subtitle: 'Local Government Unit Infrastructure Partnerships',
    icon: MapPin,
    defaultFundingSource: 'Local Government Unit',
    sampleProjects: sampleLocallyFundedProjects
  },
  'special-grants': {
    category: 'special-grants',
    title: 'Special Grants & Partnerships',
    subtitle: 'Grant-funded, Partnership & Income-Generating Projects',
    icon: Award,
    defaultFundingSource: 'Special Grant',
    sampleProjects: sampleSpecialGrantsProjects
  }
};
